# exchanges config
exchanges:
  yobit:
    apiKey: xxx
    secret: xxx
# minimum volume in btc
minimal_volume: 0.1
# spread in percent
minimum_spread: 1
# cache data for debugging purpose
save_cached_data: False
use_cached_data: False
check_wallets: False
update_cached_data: False
query_base_prices:
  # one day
  cache_expire_in: 86400
  exchange: poloniex
influxdb:
  host: 'localhost'
  post: 8086
  user: 'user'
  password: 'password'
  database: 'cryptoarbitrage'
